# Generated by Django 5.1.1 on 2025-01-16 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_doctor_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
    ]
